/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5u1kPCsdTqN
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from "@/components/ui/select";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

export function TemplatesPage() {
  return (
    <div className="flex min-h-screen w-full flex-col bg-background">
      <header className="sticky top-0 z-40 flex h-16 shrink-0 items-center border-b bg-background px-4 md:px-6">
        <a href="#" className="flex items-center gap-2 font-semibold">
          <FileCodeIcon className="h-6 w-6" />
          <span>Jinja2 Templates</span>
        </a>
        <div className="ml-auto flex items-center gap-4">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" size="icon" className="h-8 w-8">
                <SearchIcon className="h-4 w-4" />
                <span className="sr-only">Search</span>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-80">
              <DropdownMenuItem>
                <div className="relative w-full">
                  <Input
                    type="search"
                    placeholder="Search templates..."
                    className="w-full rounded-md bg-background pl-8 pr-4"
                  />
                  <SearchIcon className="absolute left-2 top-2 h-4 w-4 text-muted-foreground" />
                </div>
              </DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem>
                <div className="flex items-center justify-between">
                  <span>Search in:</span>
                  <Select>
                    <SelectTrigger className="w-[120px]">
                      <SelectValue placeholder="All" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All</SelectItem>
                      <SelectItem value="name">Name</SelectItem>
                      <SelectItem value="content">Content</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
          <Button>New Template</Button>
        </div>
      </header>
      <main className="flex-1 overflow-auto">
        <div className="grid grid-cols-[240px_1fr] gap-6 p-6">
          <div className="flex flex-col gap-4">
            <Card>
              <CardHeader>
                <CardTitle>Templates</CardTitle>
              </CardHeader>
              <CardContent>
                <nav className="grid gap-2">
                  <a
                    href="#"
                    className="flex items-center justify-between rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted"
                  >
                    <span>Header</span>
                    <ChevronRightIcon className="h-4 w-4 text-muted-foreground" />
                  </a>
                  <a
                    href="#"
                    className="flex items-center justify-between rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted"
                  >
                    <span>Footer</span>
                    <ChevronRightIcon className="h-4 w-4 text-muted-foreground" />
                  </a>
                  <a
                    href="#"
                    className="flex items-center justify-between rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted"
                  >
                    <span>Hero</span>
                    <ChevronRightIcon className="h-4 w-4 text-muted-foreground" />
                  </a>
                  <a
                    href="#"
                    className="flex items-center justify-between rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted"
                  >
                    <span>Features</span>
                    <ChevronRightIcon className="h-4 w-4 text-muted-foreground" />
                  </a>
                  <a
                    href="#"
                    className="flex items-center justify-between rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted"
                  >
                    <span>Pricing</span>
                    <ChevronRightIcon className="h-4 w-4 text-muted-foreground" />
                  </a>
                </nav>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Schemas</CardTitle>
              </CardHeader>
              <CardContent>
                <nav className="grid gap-2">
                  <a
                    href="#"
                    className="flex items-center justify-between rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted"
                  >
                    <span>Product</span>
                    <ChevronRightIcon className="h-4 w-4 text-muted-foreground" />
                  </a>
                  <a
                    href="#"
                    className="flex items-center justify-between rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted"
                  >
                    <span>User</span>
                    <ChevronRightIcon className="h-4 w-4 text-muted-foreground" />
                  </a>
                  <a
                    href="#"
                    className="flex items-center justify-between rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted"
                  >
                    <span>Order</span>
                    <ChevronRightIcon className="h-4 w-4 text-muted-foreground" />
                  </a>
                </nav>
              </CardContent>
            </Card>
          </div>
          <div className="flex flex-col gap-6">
            <Card className="flex-1">
              <CardHeader>
                <CardTitle>Header Template</CardTitle>
                <div className="ml-auto flex items-center gap-2">
                  <Button variant="outline" size="icon">
                    <PenIcon className="h-4 w-4" />
                    <span className="sr-only">Edit</span>
                  </Button>
                  <Button variant="outline" size="icon">
                    <CopyIcon className="h-4 w-4" />
                    <span className="sr-only">Copy</span>
                  </Button>
                  <Button variant="outline" size="icon">
                    <TrashIcon className="h-4 w-4" />
                    <span className="sr-only">Delete</span>
                  </Button>
                </div>
              </CardHeader>
              <CardContent className="flex-1">
                <div className="relative h-full w-full">
                  <div className="h-full w-full" />
                </div>
              </CardContent>
            </Card>
            <div className="grid grid-cols-2 gap-6">
              <Card>
                <CardHeader>
                  <CardTitle>Variables</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-4">
                    <div className="grid gap-1">
                      <Label htmlFor="site-name">Site Name</Label>
                      <Input id="site-name" defaultValue="My Website" />
                    </div>
                    <div className="grid gap-1">
                      <Label htmlFor="nav-links">Navigation Links</Label>
                      <Textarea
                        id="nav-links"
                        defaultValue={`[
  {
    "label": "Home",
    "url": "/"
  },
  {
    "label": "About",
    "url": "/about"
  },
  {
    "label": "Products",
    "url": "/products"
  },
  {
    "label": "Contact",
    "url": "/contact"
  }
]`}
                        rows={5}
                      />
                      <p className="text-sm text-muted-foreground">
                        Enter navigation links as a JSON array of objects with
                        "label" and "url" properties.
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Find and Replace</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-4">
                    <div className="grid gap-1">
                      <Label htmlFor="find">Find</Label>
                      <Input id="find" placeholder="Enter text to find" />
                    </div>
                    <div className="grid gap-1">
                      <Label htmlFor="replace">Replace</Label>
                      <Input
                        id="replace"
                        placeholder="Enter replacement text"
                      />
                    </div>
                    <Button>Replace</Button>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  );
}

function CopyIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="14" height="14" x="8" y="8" rx="2" ry="2" />
      <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />
    </svg>
  );
}

function FileCodeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 12.5 8 15l2 2.5" />
      <path d="m14 12.5 2 2.5-2 2.5" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7z" />
    </svg>
  );
}

function PenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
    </svg>
  );
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}

function TrashIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  );
}

function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
